services:
  db:
    image: postgres:16-alpine
    container_name: notes_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: newpassword
      POSTGRES_DB: test
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - notes_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: notes_backend
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: newpassword
      DB_NAME: test
      APP_MODE: "2"
    ports:
      - "8080:8080"
    networks:
      - notes_network
    stdin_open: true
    tty: true

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: notes_frontend
    ports:
      - "3000:3000"
    networks:
      - notes_network
    depends_on:
      - backend

volumes:
  postgres_data:

networks:
  notes_network:
    driver: bridge
